function requiredElement<TElement extends HTMLElement>(
  id: string,
): TElement {
  const element = document.getElementById(id);
  if (!element) {
    throw new Error(`Required popup DOM element is missing: #${id}`);
  }

  return element as TElement;
}

function queryAll<TElement extends Element>(selector: string): TElement[] {
  return Array.from(document.querySelectorAll<TElement>(selector));
}

export const popupDom = {
  header: {
    extTitle: requiredElement<HTMLHeadingElement>("ext-title"),
    extDesc: requiredElement<HTMLParagraphElement>("ext-desc"),
  },
  tabs: {
    tabButtons: queryAll<HTMLButtonElement>(".tab-button"),
    panels: queryAll<HTMLElement>(".tab-panel"),
  },
  compose: {
    promptInput: requiredElement<HTMLTextAreaElement>("prompt-input"),
    promptCounter: requiredElement<HTMLElement>("prompt-counter"),
    clearPromptBtn: requiredElement<HTMLButtonElement>("clear-prompt-btn"),
    templateSummary: requiredElement<HTMLElement>("template-summary"),
    templateSummaryLabel: requiredElement<HTMLElement>("template-summary-label"),
    templateChipList: requiredElement<HTMLElement>("template-chip-list"),
    sitesLabel: requiredElement<HTMLElement>("sites-label"),
    sitesContainer: requiredElement<HTMLElement>("sites-container"),
    toggleAllBtn: requiredElement<HTMLButtonElement>("toggle-all"),
    saveFavoriteBtn: requiredElement<HTMLButtonElement>("save-favorite-btn"),
    cancelSendBtn: requiredElement<HTMLButtonElement>("cancel-send-btn"),
    sendBtn: requiredElement<HTMLButtonElement>("send-btn"),
    statusMsg: requiredElement<HTMLElement>("status-message"),
  },
  history: {
    historySearchInput: requiredElement<HTMLInputElement>("history-search"),
    historySortSelect: requiredElement<HTMLSelectElement>("history-sort"),
    historyList: requiredElement<HTMLElement>("history-list"),
  },
  favorites: {
    favoritesSearchInput: requiredElement<HTMLInputElement>("favorites-search"),
    favoritesSortSelect: requiredElement<HTMLSelectElement>("favorites-sort"),
    favoritesList: requiredElement<HTMLElement>("favorites-list"),
  },
  settings: {
    settingsTitle: requiredElement<HTMLElement>("settings-title"),
    settingsDesc: requiredElement<HTMLElement>("settings-desc"),
    reuseExistingTabsToggle: requiredElement<HTMLInputElement>("reuse-existing-tabs-toggle"),
    reuseExistingTabsLabel: requiredElement<HTMLElement>("reuse-existing-tabs-label"),
    reuseExistingTabsDesc: requiredElement<HTMLElement>("reuse-existing-tabs-desc"),
    autoCaptureResponsesToggle: requiredElement<HTMLInputElement>("auto-capture-responses-toggle"),
    autoCaptureResponsesLabel: requiredElement<HTMLElement>("auto-capture-responses-label"),
    autoCaptureResponsesDesc: requiredElement<HTMLElement>("auto-capture-responses-desc"),
    openOptionsBtn: requiredElement<HTMLButtonElement>("open-options-btn"),
    clearHistoryBtn: requiredElement<HTMLButtonElement>("clear-history-btn"),
    exportJsonBtn: requiredElement<HTMLButtonElement>("export-json-btn"),
    importJsonBtn: requiredElement<HTMLButtonElement>("import-json-btn"),
    importJsonInput: requiredElement<HTMLInputElement>("import-json-input"),
    waitMultiplierLabel: requiredElement<HTMLElement>("wait-multiplier-label"),
    waitMultiplierRange: requiredElement<HTMLInputElement>("wait-multiplier-range"),
    waitMultiplierValue: requiredElement<HTMLElement>("wait-multiplier-value"),
  },
  serviceManagement: {
    serviceManagementTitle: requiredElement<HTMLElement>("service-management-title"),
    serviceManagementDesc: requiredElement<HTMLElement>("service-management-desc"),
    addServiceBtn: requiredElement<HTMLButtonElement>("add-service-btn"),
    resetSitesBtn: requiredElement<HTMLButtonElement>("reset-sites-btn"),
    managedSitesList: requiredElement<HTMLElement>("managed-sites-list"),
    serviceEditor: requiredElement<HTMLElement>("service-editor"),
    serviceEditorTitle: requiredElement<HTMLElement>("service-editor-title"),
    serviceEditorDesc: requiredElement<HTMLElement>("service-editor-desc"),
    serviceNameLabel: requiredElement<HTMLElement>("service-name-label"),
    serviceNameInput: requiredElement<HTMLInputElement>("service-name-input"),
    serviceUrlLabel: requiredElement<HTMLElement>("service-url-label"),
    serviceUrlInput: requiredElement<HTMLInputElement>("service-url-input"),
    serviceInputSelectorLabel: requiredElement<HTMLElement>("service-input-selector-label"),
    serviceInputSelectorInput: requiredElement<HTMLInputElement>("service-input-selector-input"),
    testSelectorBtn: requiredElement<HTMLButtonElement>("test-selector-btn"),
    serviceInputTypeLabel: requiredElement<HTMLElement>("service-input-type-label"),
    serviceSubmitSelectorLabel: requiredElement<HTMLElement>("service-submit-selector-label"),
    serviceSubmitSelectorInput: requiredElement<HTMLInputElement>("service-submit-selector-input"),
    serviceSubmitMethodLabel: requiredElement<HTMLElement>("service-submit-method-label"),
    serviceSubmitMethodSelect: requiredElement<HTMLSelectElement>("service-submit-method-select"),
    serviceAdvancedTitle: requiredElement<HTMLElement>("service-advanced-title"),
    serviceFallbackSelectorsLabel: requiredElement<HTMLElement>("service-fallback-selectors-label"),
    serviceFallbackSelectorsInput: requiredElement<HTMLTextAreaElement>("service-fallback-selectors-input"),
    serviceAuthSelectorsLabel: requiredElement<HTMLElement>("service-auth-selectors-label"),
    serviceAuthSelectorsInput: requiredElement<HTMLTextAreaElement>("service-auth-selectors-input"),
    serviceHostnameAliasesLabel: requiredElement<HTMLElement>("service-hostname-aliases-label"),
    serviceHostnameAliasesInput: requiredElement<HTMLTextAreaElement>("service-hostname-aliases-input"),
    serviceSupportedRoutesLabel: requiredElement<HTMLElement>("service-supported-routes-label"),
    serviceSupportedRoutesInput: requiredElement<HTMLTextAreaElement>("service-supported-routes-input"),
    servicePermissionPreview: requiredElement<HTMLElement>("service-permission-preview"),
    serviceVerifiedAtLabel: requiredElement<HTMLElement>("service-verified-at-label"),
    serviceVerifiedAtInput: requiredElement<HTMLInputElement>("service-verified-at-input"),
    serviceVerifiedRouteLabel: requiredElement<HTMLElement>("service-verified-route-label"),
    serviceVerifiedRouteInput: requiredElement<HTMLInputElement>("service-verified-route-input"),
    serviceVerifiedAuthStateLabel: requiredElement<HTMLElement>("service-verified-auth-state-label"),
    serviceVerifiedAuthStateSelect: requiredElement<HTMLSelectElement>("service-verified-auth-state-select"),
    serviceVerifiedLocaleLabel: requiredElement<HTMLElement>("service-verified-locale-label"),
    serviceVerifiedLocaleInput: requiredElement<HTMLInputElement>("service-verified-locale-input"),
    serviceVerifiedVersionLabel: requiredElement<HTMLElement>("service-verified-version-label"),
    serviceVerifiedVersionInput: requiredElement<HTMLInputElement>("service-verified-version-input"),
    serviceWaitLabel: requiredElement<HTMLElement>("service-wait-label"),
    serviceWaitRange: requiredElement<HTMLInputElement>("service-wait-range"),
    serviceWaitValue: requiredElement<HTMLElement>("service-wait-value"),
    serviceColorLabel: requiredElement<HTMLElement>("service-color-label"),
    serviceColorInput: requiredElement<HTMLInputElement>("service-color-input"),
    serviceIconLabel: requiredElement<HTMLElement>("service-icon-label"),
    serviceIconInput: requiredElement<HTMLInputElement>("service-icon-input"),
    serviceEnabledLabel: requiredElement<HTMLElement>("service-enabled-label"),
    serviceEnabledInput: requiredElement<HTMLInputElement>("service-enabled-input"),
    serviceTestResult: requiredElement<HTMLElement>("service-test-result"),
    serviceEditorError: requiredElement<HTMLElement>("service-editor-error"),
    serviceEditorCancel: requiredElement<HTMLButtonElement>("service-editor-cancel"),
    serviceEditorSave: requiredElement<HTMLButtonElement>("service-editor-save"),
  },
  modals: {
    templateModal: requiredElement<HTMLElement>("template-modal"),
    templateModalTitle: requiredElement<HTMLElement>("template-modal-title"),
    templateModalDesc: requiredElement<HTMLElement>("template-modal-desc"),
    templateModalClose: requiredElement<HTMLButtonElement>("template-modal-close"),
    templateModalSystemInfo: requiredElement<HTMLElement>("template-modal-system-info"),
    templateFields: requiredElement<HTMLElement>("template-fields"),
    templatePreviewLabel: requiredElement<HTMLElement>("template-preview-label"),
    templatePreview: requiredElement<HTMLElement>("template-preview"),
    templateModalError: requiredElement<HTMLElement>("template-modal-error"),
    templateModalCancel: requiredElement<HTMLButtonElement>("template-modal-cancel"),
    templateModalConfirm: requiredElement<HTMLButtonElement>("template-modal-confirm"),
    favoriteModal: requiredElement<HTMLElement>("favorite-modal"),
    favoriteModalTitle: requiredElement<HTMLElement>("favorite-modal-title"),
    favoriteModalDesc: requiredElement<HTMLElement>("favorite-modal-desc"),
    favoriteModalClose: requiredElement<HTMLButtonElement>("favorite-modal-close"),
    favoriteTitleLabel: requiredElement<HTMLElement>("favorite-title-label"),
    favoriteTitleInput: requiredElement<HTMLInputElement>("favorite-title-input"),
    favoriteModeLabel: requiredElement<HTMLElement>("favorite-mode-label"),
    favoriteModeSelect: requiredElement<HTMLSelectElement>("favorite-mode-select"),
    favoritePromptWrap: requiredElement<HTMLElement>("favorite-prompt-wrap"),
    favoritePromptLabel: requiredElement<HTMLElement>("favorite-prompt-label"),
    favoritePromptInput: requiredElement<HTMLTextAreaElement>("favorite-prompt-input"),
    favoriteTargetsLabel: requiredElement<HTMLElement>("favorite-targets-label"),
    favoriteTargetsList: requiredElement<HTMLElement>("favorite-targets-list"),
    favoriteTagsLabel: requiredElement<HTMLElement>("favorite-tags-label"),
    favoriteTagsInput: requiredElement<HTMLInputElement>("favorite-tags-input"),
    favoriteFolderLabel: requiredElement<HTMLElement>("favorite-folder-label"),
    favoriteFolderInput: requiredElement<HTMLInputElement>("favorite-folder-input"),
    favoritePinnedInput: requiredElement<HTMLInputElement>("favorite-pinned-input"),
    favoritePinnedLabel: requiredElement<HTMLElement>("favorite-pinned-label"),
    favoriteScheduleEnabledRow: requiredElement<HTMLElement>("favorite-schedule-enabled-row"),
    favoriteScheduleEnabled: requiredElement<HTMLInputElement>("favorite-schedule-enabled"),
    favoriteScheduleEnabledLabel: requiredElement<HTMLElement>("favorite-schedule-enabled-label"),
    favoriteScheduleFields: requiredElement<HTMLElement>("favorite-schedule-fields"),
    favoriteScheduledAtLabel: requiredElement<HTMLElement>("favorite-scheduled-at-label"),
    favoriteScheduledAtInput: requiredElement<HTMLInputElement>("favorite-scheduled-at-input"),
    favoriteScheduleRepeatLabel: requiredElement<HTMLElement>("favorite-schedule-repeat-label"),
    favoriteScheduleRepeatSelect: requiredElement<HTMLSelectElement>("favorite-schedule-repeat-select"),
    favoriteSaveDefaultsRow: requiredElement<HTMLElement>("favorite-save-defaults-row"),
    favoriteSaveDefaults: requiredElement<HTMLInputElement>("favorite-save-defaults"),
    favoriteSaveDefaultsLabel: requiredElement<HTMLElement>("favorite-save-defaults-label"),
    favoriteDefaultFieldsWrap: requiredElement<HTMLElement>("favorite-default-fields-wrap"),
    favoriteDefaultFieldsLabel: requiredElement<HTMLElement>("favorite-default-fields-label"),
    favoriteDefaultFields: requiredElement<HTMLElement>("favorite-default-fields"),
    favoriteChainWrap: requiredElement<HTMLElement>("favorite-chain-wrap"),
    favoriteChainTitle: requiredElement<HTMLElement>("favorite-chain-title"),
    favoriteChainDesc: requiredElement<HTMLElement>("favorite-chain-desc"),
    favoriteChainList: requiredElement<HTMLElement>("favorite-chain-list"),
    favoriteChainAddStep: requiredElement<HTMLButtonElement>("favorite-chain-add-step"),
    favoriteModalError: requiredElement<HTMLElement>("favorite-modal-error"),
    favoriteModalCancel: requiredElement<HTMLButtonElement>("favorite-modal-cancel"),
    favoriteModalRun: requiredElement<HTMLButtonElement>("favorite-modal-run"),
    favoriteModalConfirm: requiredElement<HTMLButtonElement>("favorite-modal-confirm"),
    resendModal: requiredElement<HTMLElement>("resend-modal"),
    resendModalTitle: requiredElement<HTMLElement>("resend-modal-title"),
    resendModalDesc: requiredElement<HTMLElement>("resend-modal-desc"),
    resendModalSites: requiredElement<HTMLElement>("resend-modal-sites"),
    resendModalClose: requiredElement<HTMLButtonElement>("resend-modal-close"),
    resendModalCancel: requiredElement<HTMLButtonElement>("resend-modal-cancel"),
    resendModalConfirm: requiredElement<HTMLButtonElement>("resend-modal-confirm"),
    responsesModal: requiredElement<HTMLElement>("responses-modal"),
    responsesModalTitle: requiredElement<HTMLElement>("responses-modal-title"),
    responsesModalDesc: requiredElement<HTMLElement>("responses-modal-desc"),
    responsesModalBody: requiredElement<HTMLElement>("responses-modal-body"),
    responsesModalClose: requiredElement<HTMLButtonElement>("responses-modal-close"),
    responsesModalConfirm: requiredElement<HTMLButtonElement>("responses-modal-confirm"),
    importReportModal: requiredElement<HTMLElement>("import-report-modal"),
    importReportModalTitle: requiredElement<HTMLElement>("import-report-modal-title"),
    importReportModalDesc: requiredElement<HTMLElement>("import-report-modal-desc"),
    importReportBody: requiredElement<HTMLElement>("import-report-body"),
    importReportModalClose: requiredElement<HTMLButtonElement>("import-report-modal-close"),
    importReportModalConfirm: requiredElement<HTMLButtonElement>("import-report-modal-confirm"),
  },
  toastHost: requiredElement<HTMLElement>("toast-host"),
};
