import { DEFAULT_SETTINGS } from "../../shared/prompts";
import type { PopupState } from "../../shared/types/popup";

export const SITE_EMOJI: Record<string, string> = {
  chatgpt: "GPT",
  gemini: "Gem",
  claude: "Cl",
  grok: "Gk",
};

export const state: PopupState = {
  activeTab: "compose",
  history: [],
  comparisonNotes: [],
  favorites: [],
  historySearch: "",
  favoritesSearch: "",
  favoritesTagFilter: "",
  favoritesFolderFilter: "",
  openMenuKey: null,
  openModalId: null,
  lastFocusedElement: null,
  favoriteSaveTimers: new Map<string, number>(),
  loadedTemplateDefaults: {},
  loadedFavoriteTitle: "",
  loadedFavoriteId: "",
  templateVariableCache: {},
  pendingTemplateSend: null,
  pendingFavoriteSave: null,
  pendingFavoriteRunReason: "",
  pendingResendHistory: null,
  pendingImportSummary: null,
  runtimeSites: [],
  serviceEditor: null,
  failedSelectors: new Map(),
  favoriteJobs: [],
  lastBroadcast: null,
  lastBroadcastToastSignature: "",
  isSending: false,
  sendSafetyTimer: null,
  promptDraftSaveTimer: null,
  settings: { ...DEFAULT_SETTINGS },
  openSiteTabs: [],
  siteTargetSelections: {},
  sitePromptOverrides: {},
  openTabsWindowId: null,
  openTabsRefreshTimer: null,
  listKeyboardFocus: {
    history: -1,
    favorites: -1,
  },
};
