function byId<T extends HTMLElement = HTMLElement>(id: string): T | null {
  return document.getElementById(id) as T | null;
}

export const optionsDom = {
  navigation: {
    navButtons: Array.from(document.querySelectorAll<HTMLElement>(".nav-button")),
    pageSections: Array.from(document.querySelectorAll<HTMLElement>(".page-section")),
    pageStatus: byId("page-status"),
  },
  dashboard: {
    dashboardCards: byId("dashboard-cards"),
    onboardingChecklist: byId("onboarding-checklist"),
    serviceDonut: byId("service-donut"),
    dailyBarChart: byId("daily-bar-chart"),
    activityHeatmap: byId("activity-heatmap"),
    serviceTrend: byId("service-trend"),
    failureReasons: byId("failure-reasons"),
    strategySummary: byId("strategy-summary"),
  },
  history: {
    historyServiceFilter: byId<HTMLSelectElement>("history-service-filter"),
    historyDateFrom: byId<HTMLInputElement>("history-date-from"),
    historyDateTo: byId<HTMLInputElement>("history-date-to"),
    historyExportCsv: byId("history-export-csv"),
    historyTableWrap: byId("history-table-wrap"),
    historySelectAll: byId<HTMLInputElement>("history-select-all"),
    historySelectAllLabel: byId("history-select-all-label"),
    historyDeleteSelected: byId("history-delete-selected"),
    historyDeleteFiltered: byId("history-delete-filtered"),
    historyDelete7d: byId("history-delete-7d"),
    historyDelete30d: byId("history-delete-30d"),
    historyDelete90d: byId("history-delete-90d"),
    historyPrevPage: byId("history-prev-page"),
    historyNextPage: byId("history-next-page"),
    historyPageInfo: byId("history-page-info"),
  },
  schedules: {
    schedulesList: byId("schedules-list"),
  },
  services: {
    servicesGrid: byId("services-grid"),
    servicesHealthCenter: byId("services-health-center"),
    servicesRefreshHealthBtn: byId("services-refresh-health"),
    serviceGroupTitle: byId<HTMLInputElement>("service-group-title"),
    serviceGroupSaveBtn: byId("service-group-save"),
    serviceGroupsList: byId("service-groups-list"),
    servicesOpenManagerBtn: byId("services-open-manager"),
  },
  experiments: {
    experimentTitle: byId<HTMLInputElement>("experiment-title"),
    experimentVariants: byId<HTMLTextAreaElement>("experiment-variants"),
    experimentVariables: byId<HTMLTextAreaElement>("experiment-variables"),
    experimentTargets: byId("experiment-targets"),
    experimentPreview: byId("experiment-preview"),
    experimentSave: byId("experiment-save"),
    experimentRun: byId("experiment-run"),
    experimentPreviewOutput: byId("experiment-preview-output"),
    experimentList: byId("experiment-list"),
  },
  settings: {
    historyLimitSlider: byId<HTMLInputElement>("history-limit-slider"),
    historyLimitValue: byId("history-limit-value"),
    historyLimitNote: byId("history-limit-note"),
    autoCloseToggle: byId<HTMLInputElement>("auto-close-toggle"),
    desktopNotificationToggle: byId<HTMLInputElement>("desktop-notification-toggle"),
    reuseTabsToggle: byId<HTMLInputElement>("reuse-tabs-toggle"),
    reuseTabsSettingTitle: byId("reuse-tabs-setting-title"),
    reuseTabsSettingDesc: byId("reuse-tabs-setting-desc"),
    waitMultiplierSettingTitle: byId("wait-multiplier-setting-title"),
    waitMultiplierSlider: byId<HTMLInputElement>("wait-multiplier-slider"),
    waitMultiplierSettingValue: byId("wait-multiplier-setting-value"),
    shortcutList: byId("shortcut-list"),
    openShortcutsBtn: byId("open-shortcuts-btn"),
    settingsResetData: byId("settings-reset-data"),
    settingsExportJson: byId("settings-export-json"),
    settingsImportJson: byId("settings-import-json"),
    settingsImportJsonInput: byId<HTMLInputElement>("settings-import-json-input"),
    templatePackSensitive: byId<HTMLInputElement>("template-pack-sensitive"),
    templatePackExport: byId("template-pack-export"),
    templatePackImport: byId("template-pack-import"),
    templatePackImportInput: byId<HTMLInputElement>("template-pack-import-input"),
    templatePackList: byId("template-pack-list"),
  },
  modals: {
    historyModal: byId("history-modal"),
    historyModalClose: byId("history-modal-close"),
    historyModalMeta: byId("history-modal-meta"),
    historyModalServices: byId("history-modal-services"),
    historyModalText: byId("history-modal-text"),
    historyModalComparison: byId("history-modal-comparison"),
    importReportModal: byId("import-report-modal"),
    importReportModalClose: byId("import-report-modal-close"),
    importReportModalTitle: byId("import-report-modal-title"),
    importReportModalDesc: byId("import-report-modal-desc"),
    importReportBody: byId("import-report-body"),
  },
  toastHost: byId("toast-host"),
};
