// @ts-nocheck
export const optionsDom = {
  navigation: {
    navButtons: [...document.querySelectorAll(".nav-button")],
    pageSections: [...document.querySelectorAll(".page-section")],
    pageStatus: document.getElementById("page-status"),
  },
  dashboard: {
    dashboardCards: document.getElementById("dashboard-cards"),
    onboardingChecklist: document.getElementById("onboarding-checklist"),
    serviceDonut: document.getElementById("service-donut"),
    dailyBarChart: document.getElementById("daily-bar-chart"),
    activityHeatmap: document.getElementById("activity-heatmap"),
    serviceTrend: document.getElementById("service-trend"),
    failureReasons: document.getElementById("failure-reasons"),
    strategySummary: document.getElementById("strategy-summary"),
  },
  history: {
    historyServiceFilter: document.getElementById("history-service-filter"),
    historyDateFrom: document.getElementById("history-date-from"),
    historyDateTo: document.getElementById("history-date-to"),
    historyExportCsv: document.getElementById("history-export-csv"),
    historyTableWrap: document.getElementById("history-table-wrap"),
    historySelectAll: document.getElementById("history-select-all"),
    historySelectAllLabel: document.getElementById("history-select-all-label"),
    historyDeleteSelected: document.getElementById("history-delete-selected"),
    historyDeleteFiltered: document.getElementById("history-delete-filtered"),
    historyDelete7d: document.getElementById("history-delete-7d"),
    historyDelete30d: document.getElementById("history-delete-30d"),
    historyDelete90d: document.getElementById("history-delete-90d"),
    historyPrevPage: document.getElementById("history-prev-page"),
    historyNextPage: document.getElementById("history-next-page"),
    historyPageInfo: document.getElementById("history-page-info"),
  },
  schedules: {
    schedulesList: document.getElementById("schedules-list"),
  },
  services: {
    servicesGrid: document.getElementById("services-grid"),
    servicesHealthCenter: document.getElementById("services-health-center"),
    servicesRefreshHealthBtn: document.getElementById("services-refresh-health"),
    serviceGroupTitle: document.getElementById("service-group-title"),
    serviceGroupSaveBtn: document.getElementById("service-group-save"),
    serviceGroupsList: document.getElementById("service-groups-list"),
    servicesOpenManagerBtn: document.getElementById("services-open-manager"),
  },
  experiments: {
    experimentTitle: document.getElementById("experiment-title"),
    experimentVariants: document.getElementById("experiment-variants"),
    experimentVariables: document.getElementById("experiment-variables"),
    experimentTargets: document.getElementById("experiment-targets"),
    experimentPreview: document.getElementById("experiment-preview"),
    experimentSave: document.getElementById("experiment-save"),
    experimentRun: document.getElementById("experiment-run"),
    experimentPreviewOutput: document.getElementById("experiment-preview-output"),
    experimentList: document.getElementById("experiment-list"),
  },
  settings: {
    historyLimitSlider: document.getElementById("history-limit-slider"),
    historyLimitValue: document.getElementById("history-limit-value"),
    historyLimitNote: document.getElementById("history-limit-note"),
    autoCloseToggle: document.getElementById("auto-close-toggle"),
    desktopNotificationToggle: document.getElementById("desktop-notification-toggle"),
    reuseTabsToggle: document.getElementById("reuse-tabs-toggle"),
    reuseTabsSettingTitle: document.getElementById("reuse-tabs-setting-title"),
    reuseTabsSettingDesc: document.getElementById("reuse-tabs-setting-desc"),
    waitMultiplierSettingTitle: document.getElementById("wait-multiplier-setting-title"),
    waitMultiplierSlider: document.getElementById("wait-multiplier-slider"),
    waitMultiplierSettingValue: document.getElementById("wait-multiplier-setting-value"),
    shortcutList: document.getElementById("shortcut-list"),
    openShortcutsBtn: document.getElementById("open-shortcuts-btn"),
    settingsResetData: document.getElementById("settings-reset-data"),
    settingsExportJson: document.getElementById("settings-export-json"),
    settingsImportJson: document.getElementById("settings-import-json"),
    settingsImportJsonInput: document.getElementById("settings-import-json-input"),
    templatePackSensitive: document.getElementById("template-pack-sensitive"),
    templatePackExport: document.getElementById("template-pack-export"),
    templatePackImport: document.getElementById("template-pack-import"),
    templatePackImportInput: document.getElementById("template-pack-import-input"),
    templatePackList: document.getElementById("template-pack-list"),
  },
  modals: {
    historyModal: document.getElementById("history-modal"),
    historyModalClose: document.getElementById("history-modal-close"),
    historyModalMeta: document.getElementById("history-modal-meta"),
    historyModalServices: document.getElementById("history-modal-services"),
    historyModalText: document.getElementById("history-modal-text"),
    historyModalComparison: document.getElementById("history-modal-comparison"),
    importReportModal: document.getElementById("import-report-modal"),
    importReportModalClose: document.getElementById("import-report-modal-close"),
    importReportModalTitle: document.getElementById("import-report-modal-title"),
    importReportModalDesc: document.getElementById("import-report-modal-desc"),
    importReportBody: document.getElementById("import-report-body"),
  },
  toastHost: document.getElementById("toast-host"),
};
