// 중앙 사이트 레지스트리.
// injector.js / popup.js / background service worker가 모두 이 배열을 기준으로 동작하도록 설계한다.
// 셀렉터는 2026-07-22 기준 공개 웹앱 DOM(selector:audit + Playwright probe) best-effort 값이며,
// 외부 서비스 UI 변경 시 이 파일만 수정하면 되도록 구성한다.

import type { SiteConfig } from "../../shared/types/models";

export const AI_SITES = Object.freeze([
  {
    id: "chatgpt",
    name: "ChatGPT",
    url: "https://chatgpt.com/",
    hostname: "chatgpt.com",
    supportedRoutes: [],
    // Prefer ProseMirror / contenteditable surfaces first; legacy #prompt-textarea kept as fallback.
    inputSelector:
      "div#prompt-textarea[contenteditable='true'], #prompt-textarea, div.ProseMirror[contenteditable='true'], textarea[aria-label*='chatgpt' i], textarea[aria-label*='채팅' i], textarea[placeholder*='ask' i]",
    fallbackSelectors: [
      "div#prompt-textarea[contenteditable='true']",
      "#prompt-textarea",
      "div.ProseMirror[contenteditable='true']",
      "textarea[aria-label*='chatgpt' i]",
      "textarea[aria-label*='채팅' i]",
      "textarea[placeholder*='ask' i]",
      "textarea.wcDTda_fallbackTextarea",
      "div[contenteditable='true'][data-id='root']",
      "main div[contenteditable='true']",
      "div[contenteditable='true'][role='textbox']",
    ],
    inputType: "contenteditable",
    submitSelector:
      "button[data-testid='send-button'], button[data-testid='composer-send-button'], button[aria-label*='send' i], button[aria-label*='보내기' i]",
    submitMethod: "click",
    selectorCheckMode: "input-and-conditional-submit",
    waitMs: 2500,
    fallback: true,
    lastVerified: "2026-08",
    verifiedAt: "2026-08-22",
    verifiedRoute: "/",
    verifiedAuthState: "logged-out",
    verifiedLocale: "ko",
    verifiedVersion: "chatgpt-web-aug-2026",
    authSelectors: [
      "form[action*='/auth']",
      "input[name='email']",
      "input[name='username']",
      "button[data-testid='login-button']",
      "a[href*='cloudflare.com']",
      "#challenge-running",
      ".cf-browser-verification",
      ".cf-challenge",
      ".cf-turnstile",
      "iframe[src*='challenges.cloudflare.com']",
    ],
  },
  {
    id: "gemini",
    name: "Gemini",
    url: "https://gemini.google.com/app",
    hostname: "gemini.google.com",
    supportedRoutes: ["/app"],
    // 2026-07-22 probe: ql-editor.textarea.new-input-ui, aria-label "Enter a prompt for Gemini"
    inputSelector:
      "div.ql-editor.textarea.new-input-ui[contenteditable='true'], div[aria-label*='prompt for Gemini' i][contenteditable='true'][role='textbox'], div[aria-label*='Gemini' i][contenteditable='true'][role='textbox'], div[contenteditable='true'][role='textbox']",
    fallbackSelectors: [
      "div.ql-editor.textarea.new-input-ui[contenteditable='true']",
      "div.ql-editor[contenteditable='true'][role='textbox']",
      "div[aria-label*='prompt for Gemini' i][contenteditable='true'][role='textbox']",
      "div[aria-label*='Gemini' i][contenteditable='true'][role='textbox']",
      "div[aria-label*='Ask Gemini' i][contenteditable='true']",
      "div[contenteditable='true'][role='textbox']",
      "div[contenteditable='true'][data-placeholder*='Gemini' i]",
      "textarea, div[contenteditable='true']",
    ],
    inputType: "contenteditable",
    submitSelector:
      "button.send-button, button[aria-label*='send' i], button[aria-label*='보내기' i], button[aria-label*='메시지 보내기' i], button[aria-label*='Submit' i], button[type='submit']",
    submitMethod: "click",
    selectorCheckMode: "input-and-conditional-submit",
    waitMs: 2500,
    fallback: true,
    lastVerified: "2026-08",
    verifiedAt: "2026-08-22",
    verifiedRoute: "/app",
    verifiedAuthState: "logged-out",
    verifiedLocale: "en-US",
    verifiedVersion: "gemini-app-aug-2026",
    authSelectors: [
      "a[href*='accounts.google.com/ServiceLogin']",
      "a[aria-label*='로그인']",
      "a[aria-label*='sign in' i]",
      "button[aria-label*='Sign in' i]",
      "button[aria-label*='로그인' i]",
      "input[type='email']",
      "input[type='password']",
    ],
  },
  {
    id: "claude",
    name: "Claude",
    url: "https://claude.ai/new",
    hostname: "claude.ai",
    supportedRoutes: ["/new"],
    inputSelector:
      "div[contenteditable='true'][role='textbox'], div[contenteditable='true'][aria-label*='Claude' i], div[contenteditable='true'][aria-label*='prompt' i], div.ProseMirror[contenteditable='true']",
    fallbackSelectors: [
      "div[contenteditable='true'][role='textbox']",
      "div[contenteditable='true'][aria-label*='Claude' i]",
      "div[contenteditable='true'][aria-label*='prompt' i]",
      "div.ProseMirror[contenteditable='true']",
      "div[contenteditable='true']",
      "fieldset div[contenteditable='true']",
      "textarea",
    ],
    inputType: "contenteditable",
    submitSelector:
      "button[aria-label='Send message'], button[aria-label*='send message' i], button[aria-label*='send' i], button[aria-label*='submit' i], button[aria-label*='보내' i], button[aria-label*='전송' i]",
    submitMethod: "click",
    selectorCheckMode: "input-and-conditional-submit",
    waitMs: 2000,
    fallback: true,
    lastVerified: "2026-08",
    verifiedAt: "2026-08-22",
    verifiedRoute: "/new",
    verifiedAuthState: "logged-out",
    verifiedLocale: "en-US",
    verifiedVersion: "claude-web-aug-2026",
    authSelectors: [
      "input#email",
      "input[type='email']",
      "input[type='password']",
      "form[action*='login']",
      "a[href*='cloudflare.com']",
      "#challenge-running",
      ".cf-browser-verification",
      ".cf-challenge",
      ".cf-turnstile",
      "iframe[src*='challenges.cloudflare.com']",
    ],
  },
  {
    id: "grok",
    name: "Grok",
    url: "https://grok.com/",
    hostname: "grok.com",
    supportedRoutes: [],
    // 2026-07-22 probe: textarea aria-label "Grok에게…", placeholder "무엇을 알고 싶으세요?"
    inputSelector:
      "textarea[aria-label*='grok' i], textarea[placeholder*='알고 싶' i], textarea[placeholder*='무엇' i], textarea[placeholder*='help' i], textarea[aria-label*='Ask' i]",
    fallbackSelectors: [
      "textarea[aria-label*='grok' i]",
      "textarea[placeholder*='알고 싶' i]",
      "textarea[placeholder*='무엇' i]",
      "textarea[placeholder*='help' i]",
      "textarea[aria-label*='Ask' i]",
      "textarea:not([aria-hidden='true'])",
      "textarea",
      "div.tiptap.ProseMirror[contenteditable='true']",
      "div.ProseMirror[contenteditable='true'][translate='no']",
      "div.ProseMirror[contenteditable='true']",
    ],
    inputType: "textarea",
    submitSelector:
      "button[data-testid='chat-submit'], button[type='submit'][aria-label*='submit' i], button[type='submit'][aria-label*='제출' i], button[aria-label*='submit' i], button[aria-label*='제출' i]",
    submitMethod: "click",
    selectorCheckMode: "input-and-conditional-submit",
    waitMs: 3000,
    fallback: true,
    lastVerified: "2026-08",
    verifiedAt: "2026-08-22",
    verifiedRoute: "/",
    verifiedAuthState: "logged-out",
    verifiedLocale: "ko",
    verifiedVersion: "grok-web-aug-2026",
    authSelectors: [
      "input[autocomplete='username']",
      "input[type='password']",
      "a[href*='/sign-in']",
      "a[href*='/login']",
      "button[aria-label*='Sign in' i]",
      "button[aria-label*='Log in' i]",
      "button[aria-label*='로그인' i]",
    ],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    url: "https://www.perplexity.ai/",
    hostname: "www.perplexity.ai",
    hostnameAliases: ["perplexity.ai"],
    supportedRoutes: [],
    inputSelector:
      "#ask-input[data-lexical-editor='true'][role='textbox'], div#ask-input[contenteditable='true'][role='textbox'], #ask-input[contenteditable='true']",
    fallbackSelectors: [
      "div#ask-input[data-lexical-editor='true'][role='textbox']",
      "div#ask-input[contenteditable='true'][role='textbox']",
      "#ask-input[contenteditable='true']",
      "div[contenteditable='true'][data-lexical-editor='true']",
      "div[contenteditable='true'][role='textbox']",
      "textarea[aria-label*='Ask' i]",
      "textarea[placeholder*='Ask'][data-testid='search-input']",
      "textarea[placeholder*='Ask']",
      "textarea[placeholder*='질문']",
      "textarea",
    ],
    inputType: "contenteditable",
    submitSelector:
      "button[aria-label*='Submit'][type='submit'], button[type='submit'][aria-label*='검색'], button[aria-label*='submit' i], button[aria-label*='제출' i], button[aria-label*='Send' i]",
    submitMethod: "click",
    selectorCheckMode: "input-and-conditional-submit",
    waitMs: 2500,
    fallback: true,
    lastVerified: "2026-08",
    verifiedAt: "2026-08-22",
    verifiedRoute: "/",
    verifiedAuthState: "soft-gated",
    verifiedLocale: "en-US",
    verifiedVersion: "perplexity-web-aug-2026",
    authSelectors: [
      "input[type='email']",
      "input[type='password']",
      "button[data-testid='login-button']",
      "a[href*='cloudflare.com']",
      "#challenge-running",
      ".cf-browser-verification",
      ".cf-challenge",
      ".cf-turnstile",
      "iframe[src*='challenges.cloudflare.com']",
    ],
  },
]) satisfies readonly SiteConfig[];

export default AI_SITES;
